server:
  port: 8080
  address: 0.0.0.0

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

